### ISSUE TITLE
Creating shared memory database fails

### ISSUE THREAD

**Issue by AxelTerizaki** [mapbox/node-sqlite3#1032]
Hello.

I'm trying to create a database in memory, run some queries on it to create tables, and then attach that same database to another one.

According to the sqlite3 documentaiton, you can create shared memory databases.

https://www.sqlite.org/inmemorydb.html see the "In-memory Databases And Shared Cache" section.

I tried something like that, but it fails :

```$ node
> var sqlite3 = require('sqlite3').verbose();
undefined
> var db = new sqlite3.Database('file::memory:?cache=shared');
undefined
> events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_CANTOPEN: unable to open database file

```

I could always attach the memory database first and then run queries on it, but since I'm reusing queries I already ran elsewhere, I'd have to copy/paste them to change table names (`table1` to `memorydb.table1`) for example.

This works fine when using a sqlite3 client in bash.

Would it be possible to implement it ?

**Comment by gms1** [comment]
At the moment this is only possible if libsqlite3.so has been compiled with "SQLITE_USE_URI=1" and node-sqlite3 has been installed using the options "--build-from-source" and "--sqlite=/path/to/sqlite3/prefix"

I have been using this method for some time now, so I am able to open a named shared memory database using an URI like:
```
'file:sqlite3orm?mode=memory&cache=shared'
```

see [enable URI format](https://github.com/gms1/node-sqlite3-orm/blob/master/docs/enable-URI.md)

Today I was browsing in the sqlite documentation, which other possibilities would exist, since the activation of the above compile-time option would be a breaking change for node-sqlite3. luckily one would only need to propagate the SQLITE_OPEN_URI constant to JavaScript

[Flags For File Open Operations](https://www.sqlite.org/c3ref/c_open_autoproxy.html)

I will therefore create a related (mini) PR; possibly also with other missing constants, such as SQLITE_OPEN_SHAREDCACHE and SQLITE_OPEN_PRIVATECACHE.
This shared cache mode is generally intended for use in embedded systems and not only required for shared memory databases

**Comment by gms1** [comment]
yes, with this solution we would just provide additional constants for use in JavaScript and would not change existing functionality
