### ISSUE TITLE
sqlite3 v69

### ISSUE THREAD

**Issue by HughGrovesArup** [mapbox/node-sqlite3#1199]
I'm trying to develop a Visual Studio Code extension that utilises sqlite3.

When I launch my extension I get the error:

"Activating extension 'undefined_publisher.designcheck2' failed: Cannot find module 'c:\Users\Hugh.Groves\Documents\VS Code Projects\DesignCheck2Extension\designcheck2\node_modules\sqlite3\lib\binding\node-v69-win32-x64\node_sqlite3.node'."

When I inspect the sqlite3/lib/binding folder I only have a node-v64-win32-x64 folder.

I have tried reinstalling and building from binary (after much effort) but can't seem to produce a v69 folder. I notice that there are no binaries available for v69.

Is there a way I can build the v69 folder I require locally? What commands would I need to issue to get this to happen?

The Visual Studio Code version details are below:

![image](https://user-images.githubusercontent.com/40033911/62228228-286a0500-b3b5-11e9-933c-9a3ac8f9e3f6.png)

**Comment by kewde** [comment]
Hi,

Are you looking to build for electron or for plain NodeJS?

Set the right environment variables and run the build.
Take a look here:
https://github.com/mapbox/node-sqlite3/blob/master/scripts/build-local.bat

**Comment by markm208** [comment]
I have a similar problem as the original poster. When I run the VS Code extension I get the error message:
 
Activating extension 'markm208.storyteller' failed: Cannot find module 'c:\Users\markm\Dropbox\st\storytellerDB\node_modules\sqlite3\lib\binding\electron-v6.1-win32-x64\node_sqlite3.node' 

The path in the error message is looking for a directory in the binding directory called:

electron-v6.1-win32-x64

I have node-v64-win32-x64 in the path instead of electron-v6.1-win32-x64.

My VS Code extension is rather old and I just recently installed the sqlite3 module from npm. 

How do I get the VS Code extension to find the correct module?

**Comment by kewde** [comment]
Hi,

Please make sure your sqlite3 is on v4.1.1
Update the version and run npm install again if it's not the case.

**Comment by anandami** [comment]
hii! i was with this problem. I uninstalled node 14v and reinstalled 12. It works!
