### ISSUE TITLE
Can't start wiki.js... How can fix this error???

### ISSUE THREAD

**Issue by andypham2808** [mapbox/node-sqlite3#1226]
Loading configuration from /Users/ngocanh/wiki/config.yml... OK
2019-10-06T14:13:27.991Z [MASTER] info: =======================================
2019-10-06T14:13:27.993Z [MASTER] info: = Wiki.js 2.0.0-beta.303 ==============
2019-10-06T14:13:27.993Z [MASTER] info: =======================================
2019-10-06T14:13:27.993Z [MASTER] info: Initializing...
2019-10-06T14:13:28.611Z [MASTER] info: Connecting to database...
2019-10-06T14:13:28.624Z [MASTER] error: Database Connection Error: ECONNREFUSED 127.0.0.1:5432

db:
  type: postgres
  # PostgreSQL / MySQL / MariaDB / MS SQL Server only:
  host: localhost
  port: 5432
  user: wikijs
  pass: wikijsrocks$
  db: wiki
  ssl: false
  # SQLite only:
  storage: path/to/database.sqlite

**Comment by kewde** [comment]
This error does not relate to this library as it seems like you are trying to connect to a Postgres DB.

**Comment by WHK102** [comment]
Same error using mysql 10.4 and nodejs 10, i can connect using mysql tool from bash but can not connect from app to same hostname (127.0.0.1).

**Comment by ErichMoraga** [comment]
I have the same issue.  @WHK102 Did you ever figure it out?

**Comment by Pdzly** [comment]
I have still this issue? Ports are open database in online no fail2ban active no ddos protection nothing

**Comment by yhojann-cl** [comment]
> I have the same issue. @WHK102 Did you ever figure it out?

No, i uninstalled wikijs and use another platform.

**Comment by VGerris** [comment]
just to clear up some things before people uninstall things because lack of knowlegde. A client is not the same as the application, especially not from localhost. Both MySQL and PostgreSQL have access limitations and privileges on localhost / cerain user often. So if your app is not connecting from and with localhost connection settings, it may not work at all.

The connection refused is clearly for PostgreSQL (port 5432) and it shows it cannot connect to the port at 127.0.0.1 ( localhost, relative to where you connect from) - so you basically do not seem to have anything running there or it is blocked by some firewall.

I think the info from wiki.js is not really clear sometimes. in my case I refer to a connection error 28000 that meant in the end the CA cert was not setup in the connection. So while psql can connect over a port forward with username and password and setup a TLS connection, the app needed the CA cert to be added as described in the documentation.

https://docs.requarks.io/install/config
