### ISSUE TITLE
Changing a js variable in a query doesn't take effect outside the scope

### ISSUE THREAD

**Issue by elmaxe** [mapbox/node-sqlite3#1306]
Is this a bug, a feature or am I dumb?

```js
db.serialize(() => {
    let someValue = 10
    console.log(someValue)

    db.all('SELECT * FROM Test', (err, rows) => {
        //Assume the Test table has 2 rows, rows.length = 2
        console.log(rows.length)
        someValue = rows.length
    }
    console.log(someValue)
})
```

Prints:
```
10
2
10
```
When it should actually be
```
10
2
2
```
---
```js
db.serialize(() => {
    let someValue = 10
    console.log(someValue)

    db.all('SELECT * FROM Test', (err, rows) => {
        //Assume the Test table has 2 rows, rows.length = 2
        console.log(rows.length)
        someValue = rows.length
        console.log(someValue)
    }
    console.log(someValue)
})
```

Prints:
```
10
2
2
10
```

To me, this behaviour is very strange, can it be explained, if it isn't a bug?

**Comment by n1ru4l** [comment]
This is expected behaviour as the callback is invoked after the console.log(someValue) at the end of the code.

This should clarify it:

```js
db.serialize(() => {
    let someValue = 10
    console.log("1", someValue)

    db.all('SELECT * FROM Test', (err, rows) => {
        //Assume the Test table has 2 rows, rows.length = 2
        console.log("3", rows.length)
        someValue = rows.length
    })
    console.log("2", someValue)
})

```

The database interaction is asynchronous and it will be called once the underlying async operation has completed. In the meantime, other code is executed. This is one of the fundamental principles of Node.js.

You should read up on Callbacks, event loop and other Node.js fundamentals, this is definitely nothing wrong with this library and this issue should be closed.
