### ISSUE TITLE
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by KotoriK** [mapbox/node-sqlite3#1434]
# Environment:
* Linux 5.0.11-1.el7.elrepo.x86_64
* node v15.6.0
* node-gyp v7.1.2 (installed globally)
* Python version 2.7.5
# Full Log
```bash
$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.6.0 | linux | x64
gyp info find Python using Python version 2.7.5 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '**project_directory**/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '**user_root**/.cache/node-gyp/15.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=**user_root**/.cache/node-gyp/15.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=**user_root**/.cache/node-gyp/15.6.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=**project_directory**/node_modules/sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:379:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:285:12)
gyp ERR! System Linux 5.0.11-1.el7.elrepo.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd **project_directory**/node_modules/sqlite3
gyp ERR! node -v v15.6.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
``````
seem like the same problem with #851 #766

**Comment by KotoriK** [comment]
FINALLY SOLVED.
For my environment, manually add ```module_name=``` and ```module_path=***your_project_root/node_modules/sqlite3/lib/binding/node-v88-linux-x64```after ```node-gyp rebuild``` ,  wait for building, and then the project can properly find `sqlite` module.
So why nobody reply on any of these same issues? That could save people lives.

**Comment by cyrilfr** [comment]
Hi @KotoriK , how did you manage to manually add module_name and module_path? Where do you set those parameters? Thanks.

**Comment by KotoriK** [comment]
> Hi @KotoriK , how did you manage to manually add `module_name` and `module_path`? Where do you set those parameters? Thanks. I'm having the same issue on Ubuntu 20.04 with Node.js v10.19.0, sqlite3 v4.2.0 and node-gyp v6.1.0.
> 
> 
add as arguments after "node-gyp rebuild". like "node-gyp rebuild --module-name=balabala"

**Comment by joao-paulo-parity** [comment]
I was having this issue on CI. The problem is that one of this package's lifecycle scripts (more specifically, `install` or `postinstall`) are not behaving correctly.

`install` is defined [here](https://github.com/mapbox/node-sqlite3/blob/60a022c511a37788e652c271af23174566a80c30/package.json#L64); to install without triggering it

`npm {ci,install} --ignore-scripts`

Then compile from source ([mentioned here](https://github.com/mapbox/node-sqlite3#source-install))

`cd ./node_modules/sqlite3 && npm install --build-from-source`

Note: `build-from-source` is a feature of [node-pre-gyp](https://github.com/mapbox/node-pre-gyp).

---

Now, I've noticed this is not as good as a workaround for local development - ideally you'd want to have `npm install` "just work". I'm afraid that, being a lifecycle script, it might not be solvable without patching the package, but I have yet to confirm this.

**Comment by joao-paulo-parity** [comment]
I'm noticing I'm not having the installation issue described above if I upgrade to 5.0.2. Might be related to https://github.com/mapbox/node-sqlite3/commit/0eba2cd891005e55e1d93719ca8463a894dc79f0.

@kewde pinging since you authored those changes. Please check out https://github.com/mapbox/node-sqlite3/issues/1434#issuecomment-783104389 and https://github.com/mapbox/node-sqlite3/pull/1441 when you have the time. As it currently is, for those on 5.0.1, the "workaround" I mentioned of using `--ignore-scripts` is sub-optimal because it might break other packages unintentionally.

**Comment by KotoriK** [comment]
I've tried sqlite3@5.0.2 on the same environment and it threw the same error.
After rechecked ```package.json```, I found it seems like a ```node-pre-gyp``` issue. According to munual, if functions normally, ```node-pre-gyp``` should read and apply those variables from ```binary```  in ```package.json```, however it doesn't.
I used the latest ```@mapbox/node-pre-gyp```(installed globally) for the above test.

**Comment by kewde** [comment]
Thank you for submitting this issue, it's greatly appreciated.

I've merged pull requests that may impact this, please clone `master` and check again.
Ping me if the issue persists - I can not replicate it however.

**Comment by KotoriK** [comment]
> Thank you for submitting this issue, it's greatly appreciated.
> 
> I've merged pull requests that may impact this, please clone `master` and check again.
> Ping me if the issue persists - I can not replicate it however.

It works. Thanks.

**Comment by Nisthar** [comment]
> > Thank you for submitting this issue, it's greatly appreciated.
> > I've merged pull requests that may impact this, please clone `master` and check again.
> > Ping me if the issue persists - I can not replicate it however.
> 
> It works. Thanks.

How did you fix it?

**Comment by migralito** [comment]
what is supposed to be the module name??

**Comment by Solpapaya** [comment]
@migralito the module_name and module_path is inside the package.json of the module you want to install
