### ISSUE TITLE
best practice use node-sqlite3 in express app

### ISSUE THREAD

**Issue by angelochen960** [mapbox/node-sqlite3#286]
Hi,

what is a good practice to use node-sqlite3 in an Express App? do we have to open and close db for every insert? thanks,

Angelo

**Comment by michael-ts** [comment]
@kkaefer Can you expand on this?  My assumption was to open the database in any request that needs to access it.  Different requests may access different databases, so with your approach is sounds like I need some kind of complicated pool management, where I basically keep open every database that any request has opened.  What if I run out of handles because too many databases are open?

The issue I am seeing is that if I have too many requests pending at once, trying to create a new sqlite3 object generates the error `SQLITE_MISUSE: out of memory`.   Should I maybe just keep a cache of what databases are open and re-use the sqlite3 object if another connection has it open, with some kind of reference counting?  This still sounds like more complexity.

**Comment by michael-ts** [comment]
@kkaefer  Also, is the assumption that the database will automatically be closed when there are no more references to it invalid?  At one point I had forgotten to close the database and yet I noticed that when no express threads were active, the databases they had opened no longer showed up as open files under the process (e.g. using something like `lsof`).

**Comment by michael-ts** [comment]
@kkaefer Strangely, if I don't open the database in read-only mode, instead of `SQLITE_MISUSE` popping up from time to time, I get `SQLITE_NOTADB` instead.
