### ISSUE TITLE
Cannot find module after building for node-webkit

### ISSUE THREAD

**Issue by csugden** [mapbox/node-sqlite3#328]
After installing for node-webkit –

`npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.10.1`

– node-webkit crashes with the error:

`Cannot find module '[...]source/node_modules/sqlite3/lib/binding/node-webkit-v14-darwin-v64/node_sqlite3.node`

The available folder in `binding` is called `node-webkit-v0.10.1-darwin-x64`. Renaming this to the expected name in the error allows the app to run.

**Comment by rss181919** [comment]
I noticed this issue is closed but I followed webkit install instructions listed on website and I get a ton of errors:

Microsoft Windows XP [Version 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

C:\NETSHARE\data\devprojects\nw\DBUtil>npm install sqlite3 --build-from-source --runtime="node-webki
t" --target_arch="ia32" --target="0.11.4"
npm WARN package.json DBUtil@ No description
npm WARN package.json DBUtil@ No repository field.
npm WARN package.json DBUtil@ No README data
\
> sqlite3@3.0.4 install C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

  unpack_sqlite_dep
  sqlite3.c
  sqlite3.vcxproj -> C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\Release\\sql
  ite3.lib
  database.cc
..\src\database.cc(134): error C2661: 'v8::Object::Set' : no overloaded function takes 3 arguments
[C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\database.cc(135): error C2661: 'v8::Object::Set' : no overloaded function takes 3 arguments
[C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
  node_sqlite3.cc
..\src\node_sqlite3.cc(23): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(24): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(25): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(26): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(28): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(30): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(32): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(33): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(34): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(35): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(36): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(37): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(38): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(39): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(40): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(41): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(42): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(43): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(44): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(45): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(46): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(47): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(48): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(49): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(50): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(51): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(52): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(53): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(54): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(55): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(56): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(57): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(58): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
  statement.cc
..\src\statement.cc(105): error C2661: 'v8::Object::Set' : no overloaded function takes 3 arguments
 [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\statement.cc(278): warning C4244: 'argument' : conversion from 'int64_t' to 'int', possible
loss of data [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxpro
j]
gyp ERR! build error
gyp ERR! stack Error: `c:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit c
ode: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Documents and Settings\admin\Application Data\npm\node
_modules\nw-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 5.1.2600
gyp ERR! command "node" "C:\\Documents and Settings\\admin\\Application Data\\npm\\node_modules\\nw-
gyp\\bin\\nw-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Release" "--module_name=node_sqlite
3" "--version=3.0.4" "--major=3" "--patch=4" "--runtime=node-webkit" "--node_abi=node-webkit-v0.11.4
" "--target=0.11.4" "--platform=win32" "--target_platform=win32" "--arch=ia32" "--target_arch=ia32"
"--module_main=./lib/sqlite3" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=C
:\\NETSHARE\\data\\devprojects\\nw\\DBUtil\\node_modules\\sqlite3\\lib\\binding\\node-webkit-v0.11.4
-win32-ia32" "--module=C:\\NETSHARE\\data\\devprojects\\nw\\DBUtil\\node_modules\\sqlite3\\lib\\bind
ing\\node-webkit-v0.11.4-win32-ia32\\node_sqlite3.node" "--remote_path=./sqlite3/v3.0.4/" "--package
_name=node-webkit-v0.11.4-win32-ia32.tar.gz" "--staged_tarball=build\\stage\\sqlite3\\v3.0.4\\node-w
ebkit-v0.11.4-win32-ia32.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/
v3.0.4/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-webkit-v0
.11.4-win32-ia32.tar.gz"
gyp ERR! cwd C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3
gyp ERR! node -v v0.10.33
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp.cmd rebuild --name=sqlite3 --configuration=
Release --module_name=node_sqlite3 --version=3.0.4 --major=3 --patch=4 --runtime=node-webkit --node_
abi=node-webkit-v0.11.4 --target=0.11.4 --platform=win32 --target_platform=win32 --arch=ia32 --targe
t_arch=ia32 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module
_path=C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\lib\binding\node-webkit-v0.11.4-wi
n32-ia32 --module=C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\lib\binding\node-webki
t-v0.11.4-win32-ia32\node_sqlite3.node --remote_path=./sqlite3/v3.0.4/ --package_name=node-webkit-v0
.11.4-win32-ia32.tar.gz --staged_tarball=build\stage\sqlite3\v3.0.4\node-webkit-v0.11.4-win32-ia32.t
ar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/ --hosted_tarball=htt
ps://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-webkit-v0.11.4-win32-ia32.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\NETSHARE\data\devprojects\nw\DBUtil\node
_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:756:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
node-pre-gyp ERR! System Windows_NT 5.1.2600
node-pre-gyp ERR! command "node" "C:\\NETSHARE\\data\\devprojects\\nw\\DBUtil\\node_modules\\sqlite3
\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3
node-pre-gyp ERR! node -v v0.10.33
node-pre-gyp ERR! node-pre-gyp -v v0.6.1
node-pre-gyp ERR! not ok
Failed to execute 'nw-gyp.cmd rebuild --name=sqlite3 --configuration=Release --module_name=node_sqli
te3 --version=3.0.4 --major=3 --patch=4 --runtime=node-webkit --node_abi=node-webkit-v0.11.4 --targe
t=0.11.4 --platform=win32 --target_platform=win32 --arch=ia32 --target_arch=ia32 --module_main=./lib
/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=C:\NETSHARE\data\devproje
cts\nw\DBUtil\node_modules\sqlite3\lib\binding\node-webkit-v0.11.4-win32-ia32 --module=C:\NETSHARE\d
ata\devprojects\nw\DBUtil\node_modules\sqlite3\lib\binding\node-webkit-v0.11.4-win32-ia32\node_sqlit
e3.node --remote_path=./sqlite3/v3.0.4/ --package_name=node-webkit-v0.11.4-win32-ia32.tar.gz --stage
d_tarball=build\stage\sqlite3\v3.0.4\node-webkit-v0.11.4-win32-ia32.tar.gz --hosted_path=https://map
box-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/ --hosted_tarball=https://mapbox-node-binary.s3.amaz
onaws.com/sqlite3/v3.0.4/node-webkit-v0.11.4-win32-ia32.tar.gz' (1)

npm ERR! sqlite3@3.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.4 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 5.1.2600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\n
pm\\bin\\npm-cli.js" "install" "sqlite3" "--build-from-source" "--runtime=node-webkit" "--target_arc
h=ia32" "--target=0.11.4"
npm ERR! cwd C:\NETSHARE\data\devprojects\nw\DBUtil
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

C:\NETSHARE\data\devprojects\nw\DBUtil>

**Comment by rss181919** [comment]
Attempting a node install and then a rebuild produces the following:

C:\NETSHARE\data\devprojects\nw\DBUtil>npm install sqlite3
npm WARN package.json DBUtil@ No description
npm WARN package.json DBUtil@ No repository field.
npm WARN package.json DBUtil@ No README data
-
> sqlite3@3.0.4 install C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\lib\binding\node-v11
-win32-ia32\node_sqlite3.node" is installed via remote
sqlite3@3.0.4 node_modules\sqlite3
└── nan@1.4.1

C:\NETSHARE\data\devprojects\nw\DBUtil>cd node_modules

C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules>cd sqlite3

C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3>nw-gyp rebuild --target="0.11.4"
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.12.4
gyp info using node@0.10.33 | win32 | ia32
gyp info spawn python
gyp info spawn args [ 'C:\\Documents and Settings\\admin\\Application Data\\npm\\node_modules\\nw-gy
p\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\NETSHARE\\data\\devprojects\\nw\\DBUtil\\node_modules\\sqlite3\\build\\co
nfig.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Documents and Settings\\admin\\Application Data\\npm\\node_modules\\nw-gy
p\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Documents and Settings\\admin\\.nw-gyp\\0.11.4\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Documents and Settings\\admin\\.nw-gyp\\0.11.4',
gyp info spawn args   '-Dmodule_root_dir=C:\\NETSHARE\\data\\devprojects\\nw\\DBUtil\\node_modules\\
sqlite3',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\NETSHARE\\data\\devprojects\\nw\\DBUtil\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: Undefined variable module_name in binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Documents and Settings\admin\Application Data\npm\no
de_modules\nw-gyp\lib\configure.js:353:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 5.1.2600
gyp ERR! command "node" "C:\\Documents and Settings\\admin\\Application Data\\npm\\node_modules\\nw-
gyp\\bin\\nw-gyp.js" "rebuild" "--target=0.11.4"
gyp ERR! cwd C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3
gyp ERR! node -v v0.10.33
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok

**Comment by Mithgol** [comment]
@rss181919 I have an impression that you are affected by the issue fixed in mapbox/node-sqlite3#369.

@springmeyer A new release of the npm package is probably necessary to prevent this issue from happening in the future.

**Comment by mwadood** [comment]
Cannot build for node webkit 
npm install nw-gyp -g
npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=ia32 --target=0.12.3

**Comment by mwadood** [comment]
E:\PERSONAL-PROJECTS\CPADTool\CPADTool\CPADTool\node_modules\sqlite3>if not de
ned npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\no
-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  cl
n )
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
Building the projects in this solution one at a time. To enable parallel build
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.
argets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform
oolset = 'v100') cannot be found. To build using the v100 build tools, please
nstall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the
urrent Visual Studio tools by selecting the Project menu or right-click the so
ution, and then selecting "Retarget solution". [E:\PERSONAL-PROJECTS\CPADTool\
PADTool\CPADTool\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fa
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mwadood\AppData\Roaming\np
node_modules\nw-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:10
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\mwadood\\AppData\\Roaming\\npm\\node_modul
\\nw-gyp\\bin\\nw-gyp.js" "build" "--fallback-to-build" "--module=E:\\PERSONAL
ROJECTS\\CPADTool\\CPADTool\\CPADTool\\node_modules\\sqlite3\\lib\\binding\\no
-webkit-v0.12.3-win32-ia32\\node_sqlite3.node" "--module_name=node_sqlite3" "-
odule_path=E:\\PERSONAL-PROJECTS\\CPADTool\\CPADTool\\CPADTool\\node_modules\\
lite3\\lib\\binding\\node-webkit-v0.12.3-win32-ia32"
gyp ERR! cwd E:\PERSONAL-PROJECTS\CPADTool\CPADTool\CPADTool\node_modules\sqli
3
gyp ERR! node -v v0.12.7
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp.cmd build --fallback-
-build --module=E:\PERSONAL-PROJECTS\CPADTool\CPADTool\CPADTool\node_modules\s
ite3\lib\binding\node-webkit-v0.12.3-win32-ia32\node_sqlite3.node --module_nam
node_sqlite3 --module_path=E:\PERSONAL-PROJECTS\CPADTool\CPADTool\CPADTool\nod
modules\sqlite3\lib\binding\node-webkit-v0.12.3-win32-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\PERSONAL-PROJECTS\
ADTool\CPADTool\CPADTool\node_modules\sqlite3\node_modules\node-pre-gyp\lib\ut
\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proc
s.js:1087:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "node" "E:\\PERSONAL-PROJECTS\\CPADTool\\CPADTool\\C
DTool\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "
stall" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\PERSONAL-PROJECTS\CPADTool\CPADTool\CPADTool\node_mod
es\sqlite3
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok
Failed to execute 'nw-gyp.cmd build --fallback-to-build --module=E:\PERSONAL-P
JECTS\CPADTool\CPADTool\CPADTool\node_modules\sqlite3\lib\binding\node-webkit-
.12.3-win32-ia32\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:
ERSONAL-PROJECTS\CPADTool\CPADTool\CPADTool\node_modules\sqlite3\lib\binding\n
e-webkit-v0.12.3-win32-ia32' (1)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\node
\\node_modules\\npm\\bin\\npm-cli.js" "install" "sqlite3" "--build-from-source
"--runtime=node-webkit" "--target_arch=ia32" "--target=0.12.3"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.0 install script 'node-pre-gyp install --fa
back-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\PERSONAL-PROJECTS\CPADTool\CPADTool\CPADTool\npm-debug.log
