### ISSUE TITLE
node-webkit v0.11.x support

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-sqlite3#404]
Latest node-sqlite3 (v3.0.5) does not compile with node-webkit v0.11.x. This is because NAN is unable to detect the version sufficiently enough to handle it. This regressed in the recent NAN versions that are needed to support node v0.12.x and io.js 1.x. More details at https://github.com/rvagg/nan/pull/238

My understanding from reading https://github.com/rvagg/nan/pull/238 is that the next action is to try building node-sqlite3 against node-webkit (aka. nw.js) v0.12.x and if that can be made to work then document clearly that v0.11.x is NOT SUPPORTED.

**Comment by Mithgol** [comment]
Starting from https://github.com/rvagg/nan/pull/238#issuecomment-70438359 some comments in rvagg/nan#238 seem to imply that current nw.js (v0.12.0-alpha2, I suppose) does not (yet) support current nan and thus @rogerwang has yet to release a newer alpha version of nw.js v0.12.x; only then can we try building anything for it.

Meanwhile it's okay to lose any support for node-webkit v0.11.x (←that's what #403 does). We need the newest nan to support the newest io.js and the newest Node v0.11.x.

**Comment by Mithgol** [comment]
NW.js v0.12.0-alpha3 was [released](https://groups.google.com/forum/#!topic/nwjs-general/heM9DRTLx5U), and it is [likely](https://github.com/rvagg/nan/pull/238#issuecomment-74276753) to have nan support already.

Tomorrow ([UTC+3](https://en.wikipedia.org/wiki/Moscow_Time)) I may try building something from a separate branch. Meanwhile I've [updated](https://github.com/mapbox/node-sqlite3/commit/500ce023bd1c09f9a86e513d93b3c87eaea494cd) the list of supported engines.

**Comment by zhangtao0x** [comment]
## In nan.h we can see as follows from line 175.
` /* io.js 1.0  */
if NODE_MODULE_VERSION >= IOJS_1_0_MODULE_VERSION \
 || NODE_VERSION_AT_LEAST(0, 11, 15)
  NAN_INLINE
  void NanSetCounterFunction(v8::CounterLookupCallback cb) {
    v8::Isolate::GetCurrent()->SetCounterFunction(cb);
  }`
#### I guess it's the reason that cause the error.Because from the wrong info we can see
`../node_modules/nan/nan.h:200:5: error: ‘SetCounterFunction’ is not a member of ‘v8::V8’
     v8::V8::SetCounterFunction(cb);
     ^` 
#### I use the nw 0.11.16 which depends on node v0.11.13,so in nan.h it go into the older v8 conditions,
#### if I change the NODE_VERSION_AT_LEAST(0,11,15) to (0,11,13) it should work.

**Comment by springmeyer** [comment]
closing, nothing actionable here. We are currenltly building for node-webkit 0.8 and 0.10 and not 0.11.
