### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by chriskinsman** [mapbox/node-sqlite3#614]
Doing something simple.  Inserting 1 million rows into a table.

I find node eventually crashes as it hits it's 1GB memory limit.

I have attached node-inspector and looked at heap snapshots and the growth doesn't appear to be in the managed heap.  It stays flat over time.  This appears to be a leak in native code.

```
var async = require('async');
var uuid = require('node-uuid');
var total = 1000000;
var count = 0;

var db = new sqlite.Database('memleak.db', sqlite.OPEN_READWRITE, function(err) {
    if(err) {
        console.error('Error creating database err: ' + err);
        process.exit(1);
    }
    else {
        async.doWhilst(function(done) {
            console.info(count);
            db.run("INSERT INTO Users(uid, id) VALUES($uid, $id)", {$uid: uuid.v4(), $id: count}, done);
        }, function() {
            return count++ < total;
        }, function(err) {
            if(err) {
                console.error('Error adding users err: ' + err);
                process.exit(1);
            }
            else {
                console.info('Done');
                process.exit(0);
            }
        });
    }
});
```

Node 4.2.2

**Comment by springmeyer** [comment]
There is not a memory leak in node-sqlite3 as far as I can tell. Instruments.app/valgrind do not report c++ land leaks. So the likely cause is that garbage collection is not happening in node.js because of the tight loop. To confirm this theory I added `gc();` call inside the `async.doWhilst(` and then ran node with `--expose-gc`. Memory stays flat in this case, which indicates that the problem is that lots of JS objects are being created and not garbage collected. The main culprit is `uuid.v4()` which allocates per loop.

So, I recommend:

 - Rethinking/re-writing your code to work in batches
 - Study and understand how garbage collection works in v8/node and across versions
 - Don't use `gc()` for anything but testing - really you need to figure out how to write code that is less aggressive and allows the vm to garbage collect every once in a while to keep memory down.
