### ISSUE TITLE
Sqlite3 not working on 32bit version linux

### ISSUE THREAD

**Issue by IrosTheBeggar** [mapbox/node-sqlite3#713]
I tried installing a node module on 32bit Ubuntu 16.04 and got an error when it tried compiling sqlite3.  I treid this on Arch 32bit as well on got the same problem.  Sqlite3 built just fine on the 64bit Ubuntu and Arch counterparts.  Any idea why this might be happening?

**Comment by ErisDS** [comment]
Hi there @IrosTheBeggar,  there are no longer any pre-built binaries supplied for this package for 32bit linux, which explains what you are seeing. For 64bit linux a pre-compiled binary is downloaded, but for 32bit linux you need to have your environment configured correctly so that your system can compile the binary itself. 

The available solutions are to either switch to 64bit linux, or follow the [install guide](https://github.com/mapbox/node-sqlite3#installing) for how to setup your environment and compile your own binary.
