### ISSUE TITLE
Drop node v0.10 support?

### ISSUE THREAD

**Issue by tmcw** [mapbox/node-sqlite3#719]
Node v4.x+ is under Long-Term Support, while v0.10 was released over 3 years ago. Supporting 0.x makes basic stuff like eslint support harder #715

**Comment by ErisDS** [comment]
Node v0.10 is end of life on 31st October, so I'd suggest that would be the right time to drop support.

**Comment by springmeyer** [comment]
I don't think we should drop node v0.10 support soon. Because node-sqlite3 is used widely I think we should support it for at least another 6 months. Running eslint for builds with node 4 and greater seems like a fine workaround.

**Comment by ErisDS** [comment]
> Because node-sqlite3 is used widely I think we should support it for at least another 6 months.

I would suggest that this is the wrong approach, for a couple of reasons.

I'm a great believer that the more of the community that throws it's support behind the EOL date for Node v0.10, the better it will be for Node.js as a whole. It sends a clear message to the wider ecosystem that EOL means EOL. This means that sysops everywhere can depend on the LTS and EOL dates for Node.js the same way they would with linux or unix software. If common packages don't drop support, it makes the EOL date fuzzy and unreliable. 

Further, If you go on supporting Node v0.10 beyond EOL, what happens if a security issue pops up that particularly effects the sqlite3 + v0.10 combo? Maybe it's a cross-that-bridge when it comes to it kind of problem, but you're entering into fuzzy territory. Again, it's just my opinion, but as a package maintainer I'd think it would be preferable to immediately drop "official" support.

Anyone who wants to continue to use v0.10 still can, by keeping their version of node-sqlite3 pinned at a version with support. However, they are choosing to run out-of-date software and therefore the burden of support falls to them and not this module.

It's just my 2c, but something I'm passion about, enough to have joined the Node.js LTS team 😉

**Comment by tmcw** [comment]
As additional context, @ErisDS is CTO of @TryGhost, which is probably one of the top or the top consumer of node-sqlite3, and Ghost is requiring Node v4 LTS or higher, so... that's a good thing.

**Comment by ErisDS** [comment]
Also for context, we will release a new version of Ghost that drops v0.10 support as soon as the announcement is made on Nodejs.org / 1st Nov.

**Comment by kkaefer** [comment]
@ErisDS thanks for your insight. Apart from changing documentation and removing node 0.10 support from the list, do you envision any code changes? It seems that Nan is ironing out all of the differences, so we wouldn't actually have to do anything to "drop" support?

**Comment by ErisDS** [comment]
As far as I know that'd be correct for this repo.

In Ghost we use `engines` and have a pre-install script which errors if the node version doesn't match what we have in `engines`. We mostly did this to try to prevent people from falling through to node-sqlite3 install errors and then reporting their issues here on this repo. Sooooo we will be updating that system to not allow 0.10 as well 😁 

That means, once we ship our no 0.10 support version all of our users will get an unsupported version error and will end up in our support and hopefully not clogging up your issue list 👯

**Comment by tjwebb** [comment]
Any update on this?

**Comment by tmcw** [comment]
Closing, not seeing maintainer interest.
