### ISSUE TITLE
sqlite3 - Binaries Packages for ARM

### ISSUE THREAD

**Issue by shalien** [mapbox/node-sqlite3#791]
Compiled on Raspberry Pi 
module : 3.1.8
link : https://cloud.unrozah.fr/index.php/s/nupy7Et5DkyMYJN
[node-v48-linux-arm.tar.gz](https://github.com/mapbox/node-sqlite3/files/827198/node-v48-linux-arm.tar.gz)

**Comment by springmeyer** [comment]
We are no longer accepted submitted binaries since its a security hole, so this has been removed from the wiki (https://github.com/mapbox/node-sqlite3/wiki/Binaries/_compare/82fa8109942292dece3d42326e9d3bed45a889fd...9a624a00f533382ec00f12141b587f5455313c67).

That said ARM binaries would be valuable, if built on travis. See https://github.com/mapbox/node-sqlite3/issues/418 for this discussion.
