### ISSUE TITLE
Do you dump the whole sqlite database into the memory?

### ISSUE THREAD

**Issue by piyushbeli** [mapbox/node-sqlite3#794]
https://github.com/kripken/sql.js/ library also doing almost same thing but putting the whole DB into the memory which is very expensive.
Can you please give some information how do you query the DB?

**Comment by Spaxe** [comment]
Almost certainly not. 

For example, if you used `spatialite.OPEN_READONLY` and pointed the `Database()` initialisation to a `.sqlite` Database, it queries the DB on the file system.

**Comment by piyushbeli** [comment]
@Spaxe Sorry, I did not understand your above statement. Do you have any example somewhere which I can see?
In the example, I see below statement which gives an impression that you load the DB in memory. I apologize if I do not understand the statement correctly.

`var sqlite3 = require('sqlite3').verbose();
var db = new sqlite3.Database(':memory:');`

**Comment by Spaxe** [comment]
@piyushbeli Of course. Take a look at the [`Database()` in API Documentation](https://github.com/mapbox/node-sqlite3/wiki/API#new-sqlite3databasefilename-mode-callback).

The following will create a DB on file instead of relying only on memory.
```
var sqlite = require('sqlite3').verbose();

// Default mode is sqlite.OPEN_READWRITE | sqlite.OPEN_CREATE
var db = new sqlite.Database('path/to/db.sqlite');

// Now you can do your queries
db.run( ... )
```

I'm working with a 1GB+ Sqlite database and can certainly tell you that it doesn't load it all to memory, only retrieves what is being queried.

**Comment by piyushbeli** [comment]
@Spaxe, Thanks for the code example. I was certainly not understanding it correctly.
It answers my query. Closing this ticket.

Appreciate your quick reply.
