### ISSUE TITLE
Warning for db.serialize()

### ISSUE THREAD

**Issue by ORESoftware** [mapbox/node-sqlite3#796]
Just wondering why you think my IDE will give me a warning when using

```js
db.serialize(function(){});
```

like so:

<img width="720" alt="screenshot 2017-03-11 19 46 58" src="https://cloud.githubusercontent.com/assets/11139560/23828842/b1dc7150-0693-11e7-8260-ff78c4d4358b.png">

**Comment by tmcw** [comment]
I'd guess you have Flowtype or TypeScript support enabled, but an incorrect typing for sqlite3 somewhere. The [definitelytyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/sqlite3/index.d.ts#L78) version looks fine.

Without more details (like what happens if you click _more_) this isn't debuggable, so closing.
