### ISSUE TITLE
feature-request - include sqlite3 as builtin module for node v9.x

### ISSUE THREAD

**Issue by kaizhu256** [mapbox/node-sqlite3#870]
i would like to push for inclusion of this module as a node v9.x builtin at https://github.com/nodejs/node/issues/15128

can anyone comment on the stability of this package and roadmap for future changes (hopefully very little change ;)?

**Comment by makamekm** [comment]
Try to use the last version...

**Comment by springmeyer** [comment]
@kaizhu256 this package is stable and there are few changes planned. I see from nodejs/node#15128 that there is not much interest from devs. That is understandable given that would add an sqlite3 dep to core which would need to be updated and tracked for security fixes. But I agree that from a user perspective it would be ideal to have node-sqlite3 in core. I'm going to close this now since there is not much more to discuss here.
