### ISSUE TITLE
sqlite buildprocess needs a lot of memory on raspberryPI3

### ISSUE THREAD

**Issue by BramTown** [mapbox/node-sqlite3#942]
Hi,

during installation of sqlite on my raspberryPI3 the raspi freezes and stop working because the buildprocess of sqlite needs too much memory / RAM.

May there is the possibility to check if memory-usage can be reduced during buildprocess on raspi?

Thanks :-)

**Comment by rzr** [comment]
Relate to:
https://github.com/mapbox/node-sqlite3/issues/597

**Comment by springmeyer** [comment]
This large memory requirement is due to us using the single-source-file (aka amalgamated) version of the libsqlite3 library. One alternative is that you could build libsqlite3 yourself, first, and then point node-sqlite3 at it using the `npm install --sqlite` flag per https://github.com/mapbox/node-sqlite3#source-install

**Comment by springmeyer** [comment]
See also #418
